name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
      - name: Retore Workload
        run: dotnet workload restore ./Float.CorCav.Behaviors.csproj
      - name: Restore dependencies
        run: dotnet restore ./Float.CorCav.Behaviors.csproj
      - name: Set Assembly Version
        run: ./build.sh --task=GitVersion --configuration=Release
      - name: Build Library
        run: dotnet build ./Float.CorCav.Behaviors.csproj --configuration Release --no-restore
      - name: Update Version
        run: sed -i "s/<Version><\/Version>/<Version>${{ github.event.release.name }}<\/Version>/" ./Float.CorCav.Behaviors.csproj
      - name: Pack and Upload
        run: dotnet pack ./Float.CorCav.Behaviors.csproj --configuration Release --no-restore
      - name: Deploy to NuGet
        env:
          FLOAT_NUGET_TOKEN: ${{ secrets.FLOAT_NUGET_TOKEN }}
        run: dotnet nuget push ./bin/Release/Float.CorCav.Behaviors.${{ github.event.release.name }}.nupkg --api-key "${FLOAT_NUGET_TOKEN}" --source https://api.nuget.org/v3/index.json
